version: "3.8"

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - nginx_conf:/etc/nginx/conf.d:ro
      - certs:/etc/nginx/certs:ro
    networks:
      - frontend
      - backend
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    depends_on:
      - glpi

  glpi:
    image: glpi/glpi
    volumes:
      - glpi_data:/var/glpi
    environment:
      - TZ=Europe/Paris
      - GLPI_SKIP_AUTOINSTALL=true
    networks:
      - backend
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:10.11
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=glpi
      - MYSQL_USER=glpi
      - MYSQL_PASSWORD_FILE=/run/secrets/db_password
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db_root_password
    secrets:
      - db_password
      - db_root_password
    networks:
      - backend
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3

  certbot:
    image: certbot/certbot
    volumes:
      - certs:/etc/letsencrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  frontend:
    external: true
    name: glpi_frontend
  backend:
    external: true
    name: glpi_backend

volumes:
  glpi_data:
    external: true
    name: glpi_data
  db_data:
    external: true
    name: glpi_db_data
  certs:
    external: true
    name: glpi_certs
  nginx_conf:
    external: true
    name: glpi_nginx_conf

secrets:
  db_password:
    external: true
    name: glpi_db_password
  db_root_password:
    external: true
    name: glpi_db_root_password
